# Generated by Django 2.2.3 on 2019-07-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('hompage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Doginfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=20)),
                ('dog_sex', models.BooleanField(choices=[(1, 'male'), (2, 'female')], default=1)),
                ('dog_pub_date', models.DateTimeField(verbose_name='date published')),
                ('dog_nation', models.IntegerField(choices=[(1, 'korea'), (2, 'USA'), (3, 'Canada')], default=1)),
                ('dog_adoptor_name', models.CharField(max_length=20)),
                ('dog_adoptor_SNS', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('goingdate', models.DateTimeField(verbose_name='가는 날짜')),
                ('email', models.EmailField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('addresss', models.CharField(max_length=50)),
            ],
        ),
    ]
